version: 2

jobs:
  build:
    shell: /bin/bash --login
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/sharp-dance
    steps:
      - checkout
      - run: ./.circleci/ci.sh
