version: 2

jobs:
  build:
    shell: /bin/bash --login
    docker:
      - image: cimg/node:19.0.1-browsers
    working_directory: ~/sharp-dance
    steps:
      - checkout
      - run: ./.circleci/ci.sh
